### PR TITLE
Upgrade go.mod package version

### PR DESCRIPTION
**Pull request by VaniHaripriya**
**Description of your changes:**

Resolves : [RHOAIENG-7310](https://issues.redhat.com/browse/RHOAIENG-7310)

Implemented fixes on my fork and imported in my personal snyk account and made sure CVE is eliminated.

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by gregsheremeta** [comment]
@VaniHaripriya 

> Merging is blocked
> The base branch requires all commits to be signed.

do `git commit --amend -s` to add the Signed-off-by line, and then force push

**Comment by VaniHaripriya** [comment]
Closing this PR as we no longer need this. snyk created some CVEs for go.mod under tekton-catalog which should be ignored.

**Pull request closed without merging**
