### PR TITLE
Update MySQL Image, add MariaDB overlay

### PR DESCRIPTION
**Pull request by gmfrasca**
**Which issue is resolved by this Pull Request:** 
Resolves #

Work In Progress, do not merge yet.

Updates the MySQL image to use RH-built images.  Also introduces a MariaDB metadata store overlay

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by anishasthana — COMMENTED** [review]
A couple files still have mysql in the name (either of the file or the object). Is that okay?

**Comment by gmfrasca** [comment]
the files with mysql remaining in the file/metadata name was by design, to allow for interchangeability between mysql and mariadb backends.

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
