### PR TITLE
feat(backend): Enable logging via environment variables for DSP components

### LINKED ISSUE #148: Improve Logging in Data Science Pipelines pods
Every time we need to enable debug logging in DSP components (API Server, persistence agent, scheduled workflow), it is a pain to make it work. We need to enable logging through manifest parameters and inject through env var in all pods to enable debugging.

### PR DESCRIPTION
**Pull request by DharmitD**
**Which issue is resolved by this Pull Request:** 
Resolves https://github.com/opendatahub-io/data-science-pipelines/issues/148

**Description of your changes:**
Enable logging for DSP components through manifest parameters and inject through env var in all pods to enable debugging.

**Testing instructions:**

Deployed a DSP instance and replaced the APISever, persistence agent and scheduled workflow images with the following images:
`quay.io/rhn_support_ddalvi/odh-ml-pipelines-api-server-container-live:v2-params`
`quay.io/rhn_support_ddalvi/odh-ml-pipelines-persistenceagent-container-live:v2-param`
`quay.io/rhn_support_ddalvi/odh-ml-pipelines-scheduledworkflow-container-live:v2-param`

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
Looks good to me @DharmitD. 
I'm just wondering if wouldn't be better to change the ZAP_LOG_LEVEL variable that I created [here](https://github.com/opendatahub-io/data-science-pipelines-operator/pull/385/files#diff-67f719806581e02b3d760efbf6de677ab53b53f7a15fb86902fd88c516b94661) to leverage this new LOG_LEVEL variable you just created, so we don't end up having two variables for very similar things.

**Comment by DharmitD** [comment]
> Looks good to me @DharmitD. I'm just wondering if wouldn't be better to change the ZAP_LOG_LEVEL variable that I created [here](https://github.com/opendatahub-io/data-science-pipelines-operator/pull/385/files#diff-67f719806581e02b3d760efbf6de677ab53b53f7a15fb86902fd88c516b94661) to leverage this new LOG_LEVEL variable you just created, so we don't end up having two variables for very similar things.

Sounds good, I will create a PR to replace the ZAP_LOG_LEVEL variable to the LOG_LEVEL variable shortly.

**Review by hbelmiro — APPROVED** [review]

**Comment by DharmitD** [comment]
Closing this PR, as this feature needs to go in the upstream first.

**Pull request closed without merging**
