### PR TITLE
Synchronize repo with upstream main

### PR DESCRIPTION
**Pull request by HumairAK**
This is an alternative pr to: https://github.com/opendatahub-io/data-science-pipelines/pull/27 to avoid the conflict.

The culprit is this commit:  [[1]](https://github.com/opendatahub-io/data-science-pipelines/pull/27/commits/f1ed8229202aa0a2e8eda528c11a06b8542ef6b2)
Which conflicts with this commit: [[1]](https://github.com/opendatahub-io/data-science-pipelines/commit/99fa74bb5a4292305c79c09f349cac35c3eb8654)

As such I've done a manual `git merge` from upstream:master, and resolved this conflict, since I can't make changes to the merging branch in the other repo.

### CODE REVIEW

**Comment by HumairAK** [comment]
Prow unit tests are failing with the following error: 

<details> 

<summary> errors.txt </summary> 

```
[36mINFO[0m[2023-01-04T19:22:20Z] ci-operator version v20230104-5a1b1f5e5      
[36mINFO[0m[2023-01-04T19:22:20Z] Loading configuration from https://config.ci.openshift.org for opendatahub-io/data-science-pipelines@master 
[36mINFO[0m[2023-01-04T19:22:20Z] Resolved source https://github.com/opendatahub-io/data-science-pipelines to master@6512f57f, merging: #64 99a0740d @HumairAK 
[36mINFO[0m[2023-01-04T19:22:25Z] Requesting 4.10 from https://api.openshift.com/api/upgrades_info/v1/graph?arch=amd64&channel=stable-4.10 
[36mINFO[0m[2023-01-04T19:22:25Z] Resolved release latest to quay.io/openshift-release-dev/ocp-release@sha256:5f9ac79c9c257c28b8b51e79a0382de285d6e4c4e4537710b7c117601d320293 
[36mINFO[0m[2023-01-04T19:22:25Z] Using namespace https://console.build02.ci.openshift.org/k8s/cluster/projects/ci-op-g008j46w 
[36mINFO[0m[2023-01-04T19:22:25Z] Running [input:root], src, unit              
[36mINFO[0m[2023-01-04T19:22:28Z] Tagging openshift/release:golang-1.18 into pipeline:root. 
[36mINFO[0m[2023-01-04T19:22:28Z] Building src                                 
[36mINFO[0m[2023-01-04T19:23:42Z] Build src succeeded after 1m15s              
[36mINFO[0m[2023-01-04T19:23:42Z] Executing test unit                          
[36mINFO[0m[2023-01-04T19:24:42Z] Logs for container test in pod unit:         
[36mINFO[0m[2023-01-04T19:24:42Z] go: downloading github.com/go-openapi/strfmt v0.21.1
go: downloading github.com/go-openapi/validate v0.20.3
go: downloading github.com/go-openapi/runtime v0.21.1
go: downloading github.com/go-openapi/errors v0.20.2
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading github.com/sirupsen/logrus v1.9.0
go: downloading github.com/tektoncd/pipeline v0.41.0
go: downloading k8s.io/apimachinery v0.25.3
go: downloading k8s.io/client-go v0.25.3
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/stretchr/testify v1.8.1
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading github.com/fsnotify/fsnotify v1.5.4
go: downloading github.com/golang/glog v1.0.0
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.16.0
go: downloading github.com/jinzhu/gorm v1.9.12
go: downloading github.com/minio/minio-go v6.0.14+incompatible
go: downloading github.com/prometheus/client_golang v1.13.0
go: downloading github.com/spf13/viper v1.10.0
go: downloading google.golang.org/grpc v1.50.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/Masterminds/squirrel v0.0.0-20190107164353-fa735ea14f09
go: downloading github.com/google/go-cmp v0.5.9
go: downloading google.golang.org/protobuf v1.28.1
go: downloading k8s.io/api v0.25.3
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/ghodss/yaml v1.0.1-0.20190212211648-25d852aebe32
go: downloading github.com/kubeflow/pipelines/api v0.0.0-20211026071850-2e3fb5efff56
go: downloading github.com/mattn/go-sqlite3 v1.9.0
go: downloading github.com/peterhellberg/duration v0.0.0-20191119133758-ec6baeebcd10
go: downloading go.uber.org/zap v1.23.0
go: downloading github.com/robfig/cron v1.2.0
go: downloading sigs.k8s.io/controller-runtime v0.11.2
go: downloading golang.org/x/net v0.1.0
go: downloading github.com/VividCortex/mysqlerr v0.0.0-20170204212430-6c6b55f8796f
go: downloading google.golang.org/genproto v0.0.0-20221014213838-99cd37c6964a
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/lestrrat-go/strftime v1.0.4
go: downloading github.com/google/addlicense v0.0.0-20200906110928-a0294312aa76
go: downloading google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.1.0
go: downloading k8s.io/code-generator v0.25.2
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/asaskevich/govalidator v0.0.0-20200907205600-7a23bdc65eef
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/oklog/ulid v1.3.1
go: downloading go.mongodb.org/mongo-driver v1.4.4
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: downloading golang.org/x/sys v0.1.0
go: downloading github.com/opentracing/opentracing-go v1.2.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/jinzhu/inflection v1.0.0
go: downloading github.com/erikstmartin/go-testdb v0.0.0-20160219214506-8d10e4a1bae5
go: downloading github.com/jinzhu/now v1.0.1
go: downloading k8s.io/klog/v2 v2.70.2-0.20220707122935-0990e81f1a8f
go: downloading k8s.io/utils v0.0.0-20220728103510-ee6ede2d64ed
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/google/gofuzz v1.2.0
go: downloading sigs.k8s.io/yaml v1.3.0
go: downloading github.com/go-openapi/analysis v0.20.1
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/go-openapi/loads v0.21.0
go: downloading github.com/go-openapi/spec v0.20.4
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/magiconair/properties v1.8.5
go: downloading github.com/spf13/afero v1.6.0
go: downloading github.com/spf13/cast v1.4.1
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading gopkg.in/ini.v1 v1.66.2
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/common v0.26.0
go: downloading github.com/lann/builder v0.0.0-20180802200727-47ae307949d0
go: downloading github.com/lib/pq v1.10.6
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/prometheus/procfs v0.8.0
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading golang.org/x/oauth2 v0.1.0
go: downloading github.com/imdario/mergo v0.3.12
go: downloading golang.org/x/term v0.1.0
go: downloading golang.org/x/time v0.0.0-20220922220347-f3bd1da661af
go: downloading github.com/go-ini/ini v1.62.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading knative.dev/pkg v0.0.0-20221011175852-714b7630a836
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.2.3
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/google/go-containerregistry v0.12.0
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading k8s.io/kube-openapi v0.0.0-20220803162953-67bda5d908f1
go: downloading sigs.k8s.io/json v0.0.0-20220713155537-f223a00ba0e2
go: downloading github.com/evanphx/json-patch v4.12.0+incompatible
go: downloading go.uber.org/atomic v1.10.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading go.uber.org/goleak v1.2.0
go: downloading github.com/go-logr/logr v1.2.3
go: downloading github.com/onsi/ginkgo v1.16.5
go: downloading github.com/onsi/gomega v1.20.1
go: downloading k8s.io/apiextensions-apiserver v0.25.2
go: downloading k8s.io/component-base v0.25.2
go: downloading github.com/lestrrat-go/envload v0.0.0-20180220234015-a3eb8ddeffcc
go: downloading github.com/google/gnostic v0.5.7-v3refs
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/josharian/intern v1.0.0
go: downloading gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
go: downloading github.com/denisenkom/go-mssqldb v0.9.0
go: downloading golang.org/x/crypto v0.1.0
go: downloading golang.org/x/text v0.4.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/pelletier/go-toml v1.9.4
go: downloading github.com/go-openapi/jsonreference v0.20.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: downloading github.com/lann/ps v0.0.0-20150810152359-62de8c46ede0
go: downloading github.com/smartystreets/goconvey v1.6.4
go: downloading cloud.google.com/go/compute v1.10.0
go: downloading google.golang.org/appengine v1.6.7
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/tidwall/pretty v1.1.0
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading golang.org/x/lint v0.0.0-20210508222113-6edffad5e616
go: downloading github.com/benbjohnson/clock v1.1.0
go: downloading gomodules.xyz/jsonpatch/v2 v2.2.0
go: downloading github.com/emicklei/go-restful/v3 v3.8.0
go: downloading github.com/go-logr/zapr v1.2.3
go: downloading github.com/blendle/zapdriver v1.3.1
go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
go: downloading k8s.io/gengo v0.0.0-20220613173612-397b4ae3bce7
go: downloading cloud.google.com/go v0.104.0
go: downloading github.com/kr/pretty v0.3.0
go: downloading github.com/golang-sql/civil v0.0.0-20190719163853-cb61b32ac6fe
go: downloading github.com/onsi/ginkgo/v2 v2.1.6
go: downloading github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
go: downloading contrib.go.opencensus.io/exporter/ocagent v0.7.1-0.20200907061046-05415f1de66d
go: downloading contrib.go.opencensus.io/exporter/prometheus v0.4.0
go: downloading go.opencensus.io v0.22.5
go: downloading github.com/census-instrumentation/opencensus-proto v0.3.0
go: downloading github.com/go-stack/stack v1.8.0
go: downloading github.com/nxadm/tail v1.4.8
go: downloading golang.org/x/tools v0.1.12
go: downloading github.com/evanphx/json-patch/v5 v5.6.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/jtolds/gls v4.20.0+incompatible
go: downloading github.com/smartystreets/assertions v0.0.0-20190401211740-f487f9de1cd3
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/rogpeppe/go-internal v1.8.0
go: downloading github.com/cloudevents/sdk-go/v2 v2.12.0
go: downloading github.com/prometheus/statsd_exporter v0.21.0
go: downloading google.golang.org/api v0.100.0
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/gopherjs/gopherjs v0.0.0-20200217142428-fce0ec30dd00
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/kelseyhightower/envconfig v1.4.0
go: downloading github.com/go-kit/log v0.2.0
go: downloading github.com/go-logfmt/logfmt v0.5.1
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading golang.org/x/mod v0.6.0
go test -v -cover ./backend/src/apiserver/...
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/syscall.go:83:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/syscall_linux.go:2255:9: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/syscall_unix.go:118:7: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/sysvshm_unix.go:33:7: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
# sigs.k8s.io/json/internal/golang/encoding/json
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:158:16: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:297:15: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:96:31: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:177:35: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:428:37: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:937:48: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:1143:45: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:1160:42: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:1195:52: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:1261:42: undeclared name: any (requires version go1.18 or later)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:158:16: too many errors
# go.uber.org/atomic
vendor/go.uber.org/atomic/pointer_go118.go:28:14: type parameter requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:28:16: undeclared name: any (requires version go1.18 or later)
vendor/go.uber.org/atomic/pointer_go118.go:34:17: type parameter requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:34:19: undeclared name: any (requires version go1.18 or later)
vendor/go.uber.org/atomic/pointer_go118.go:34:38: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:35:15: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:43:17: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:48:17: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:53:17: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:58:17: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:35:15: too many errors
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/archive [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/auth [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/client [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/common [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/filter [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/list [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/resource [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/server [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/storage [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/template [build failed]
make: *** [run-apiserver-unittests] Error 2
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-01-04T19:24:40Z"} 
[36mINFO[0m[2023-01-04T19:24:45Z] Ran for 2m24s                                
[31mERRO[0m[2023-01-04T19:24:45Z] Some steps failed:                           
[31mERRO[0m[2023-01-04T19:24:45Z] 
  * could not run steps: step unit failed: test "unit" failed: the pod ci-op-g008j46w/unit failed after 59s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 2, reason Error
---
undeclared name: any (requires version go1.18 or later)
vendor/go.uber.org/atomic/pointer_go118.go:34:38: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:35:15: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:43:17: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:48:17: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:53:17: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:58:17: type instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
vendor/go.uber.org/atomic/pointer_go118.go:35:15: too many errors
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/archive [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/auth [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/client [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/common [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/filter [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/list [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/resource [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/server [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/storage [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/template [build failed]
make: *** [run-apiserver-unittests] Error 2
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-01-04T19:24:40Z"}
--- 
[36mINFO[0m[2023-01-04T19:24:45Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:running_pod' 

```

</details>

I think this issue may be related to upstream and how `go mod vendor` works. You can reproduce this error by using a golang image with the same go version (1.18.1) and the upstream `kfp-tekton` repo. For example: 

```bash
podman run --rm -it golang:1.18.1 sh
git clone https://github.com/kubeflow/kfp-tekton
cd kfp-tekton
go mod tidy
go mod vendor
make run-go-unittests
```

This will work. But by default go build is not using the vendored packages, to enable this you need to set: `GOFLAGS=-mod=vendor`. For example: 

```bash
export GOFLAGS=-mod=vendor
make run-go-unittests
```

This should fail with the error we are seeing. I noticed that we can force this to work by using `go mod tidy -go=1.18`: 

```bash
go mod tidy -go=1.18
go mod vendor
make run-go-unittests
```

This would require amending [this line.](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/data-science-pipelines/opendatahub-io-data-science-pipelines-master.yaml#L27). However I'm still not quite certain of the implications of this. Still looking into it.

Another option would be to not use vendored packages (I'm not sure why they are used here, but if the flag is enabled in the ci container and cannot be changed then this is a non-option).

**Comment by DharmitD** [comment]
> Prow unit tests are failing with the following error:
> 
> errors.txt
> I think this issue may be related to upstream and how `go mod vendor` works. You can reproduce this error by using a golang image with the same go version (1.18.1) and the upstream `kfp-tekton` repo. For example:
> 
> ```shell
> podman run --rm -it golang:1.18.1 sh
> git clone https://github.com/kubeflow/kfp-tekton
> cd kfp-tekton
> go mod tidy
> go mod vendor
> make run-go-unittests
> ```
> 
> This will work. But by default go build is not using the vendored packages, to enable this you need to set: `GOFLAGS=-mod=vendor`. For example:
> 
> ```shell
> export GOFLAGS=-mod=vendor
> make run-go-unittests
> ```
> 
> This should fail with the error we are seeing. I noticed that we can force this to work by using `go mod tidy -go=1.18`:
> 
> ```shell
> go mod tidy -go=1.18
> go mod vendor
> make run-go-unittests
> ```
> 
> This would require amending [this line.](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/data-science-pipelines/opendatahub-io-data-science-pipelines-master.yaml#L27). However I'm still not quite certain of the implications of this. Still looking into it.
> 
> Another option would be to not use vendored packages (I'm not sure why they are used here, but if the flag is enabled in the ci container and cannot be changed then this is a non-option).

I don't see any harm in trying out option #1, i.e., amending `go mod tidy -go=1.18` in the OpenShift CI code. You could create a PR on the release repository with the change to test it out, that would spin up some test jobs.

**Comment by HumairAK** [comment]
I think the reasons for the error are due to:  https://go.dev/ref/mod#go-mod-file-go 

> As of the Go 1.17 release, if the go directive is missing, go 1.16 is assumed 

And [go mod vendor does not record go versions for deps](https://github.com/golang/go/issues/54908#issuecomment-1238674155) when main modules go directive is `< go 1.17`, for us it's `go 1.13`


> I don't see any harm in trying out option https://github.com/opendatahub-io/data-science-pipelines/pull/1, i.e., amending go mod tidy -go=1.18 in the OpenShift CI code.

Yeah I just noticed that using `go mod tidy -go=1.18` changes the the go directive for the main module, in this case kupeflow pipelines. I thought this could introduce incompatiblies to the build, but apparently[ all Go 1 versions are backwards compatible at the source level](https://tip.golang.org/doc/go1compat#expectations), so this should be a safe change

**Comment by HumairAK** [comment]
looks like https://github.com/openshift/release/pull/35199 fixed the issue

I've also tested this branch in ocp and was able to successfully run flip-coin pipeline.

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
