### PR TITLE
Move Visualization Server and Viewer CRD to a separate overlay

### PR DESCRIPTION
**Pull request by rimolive**
**Which issue is resolved by this Pull Request:** 
https://issues.redhat.com/browse/RHODS-6515

**Description of your changes:**
Move Visualization Server and Viewer to a separate overlay in ODH manifests

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by anishasthana** [comment]
cc @gregsheremeta

**Comment by gregsheremeta** [comment]
the code change looks good, but since there's no link to a ticket, we should add a summary of why we're doing this.

**Comment by gregsheremeta** [comment]
> you cannot LGTM your own PR.
ha, that's adorable

**Pull request merged**
