### PR TITLE
feat(backend): Source ObjStore Creds from Env in Tekton Template

### LINKED ISSUE #90: Remove hardcoded reference to mlpipeline-minio-artifact
/kind feature

**Description:**
There is a Secret 'mlpipeline-minio-artifact' that has a hardcoded reference in `backend/src/apiserver/template/tekton_template.go`.  Implement a way to get the secret name, keys, and values from the apiserver env vars.

### PR DESCRIPTION
**Pull request by gmfrasca**
**Which issue is resolved by this Pull Request:** 
Resolves #90 

**Description of your changes:**

**Environment tested:**

* Python Version (use `python --version`): 3.11
* Tekton Version (use `tkn version`): 0.30.1
* Kubernetes Version (use `kubectl version`): 1.20
* OS (e.g. from `/etc/os-release`): Fedora 37

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by gmfrasca** [comment]
**Testing Instructions**:

1. Deploy a DSP stack (make sure to scale down operator if this is through DSPO)
2. Copy data form `mlpipeline-minio-artifact` via `oc get Secret -oyaml mlpipeline-minio-artifact`
3. Create new secret named `s3-secret` and paste the `data` section from old secret there (no need to bother decoding the b64 data), See below for artifact.
4. Update the `accesskey` and `secretkey` keys in the data to `foo_accesskey` and `bar_accesskey` to verify there's no magic keywords here either
5. For both the APIServer and UI Deployments: Update the spec.templates.spec.containers.env.valueFrom.secretKeyRef `name`s that referenced `mlpipelines-minio-artifact` to `s3-secret`, and `values` to `foo_accesskey` or `bar_secretkey`.
6. Verify new APIServer and UI Pods spin up
7. Once fully up, kick off a new PipelineRun using the default Pipeline
9. Using the accesskey and secret key from the `s3-secret`, log into minio and check if new artifacts are present in /artifacts prefix
  a. If using minio, create a Route pointed to the minio service on port 9000 and use the credentials provided in `s3-secret`

**Comment by HumairAK** [comment]
/lgtm
/approve

@gmfrasca can you also make this pr to: https://github.com/kubeflow/kfp-tekton

**Comment by HumairAK** [comment]
/hold

sec want to see something

**Pull request merged**
