### PR TITLE
fix(manifests): Add missing default-config kustomization.yaml

### PR DESCRIPTION
**Pull request by gmfrasca**
**Description of your changes:**
Add missing kustomization.yaml for default-configs overlay

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by LaVLaS** [comment]
Merging via admin override since this should fix the current blocker for https://github.com/openshift/release/pull/33037

**Pull request merged**
